# Site settings
title: å–‚é²¸é±¼ ğŸ³
tag_text: ä¸€ç®ªé£Ÿï¼Œä¸€ç“¢é¥®ï¼Œåœ¨é™‹å··
description: Just some notes.
# url: weijingyu.com
baseurl: "/clean"

collections:
  - notes

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
